# Generated by Django 5.0.6 on 2024-10-19 11:48

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('color', models.CharField(blank=True, choices=[('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE'), ('PURPLE', 'PURPLE'), ('BLUE', 'BLUE'), ('GRAY', 'GRAY'), ('RED', 'RED'), ('YELLOW', 'YELLOW')], default='BLACK', max_length=100, null=True, verbose_name='Цвет товара')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='no_image.jpg', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='product_images/', verbose_name='Основная фотография')),
                ('status', models.CharField(blank=True, choices=[('в наличии', 'В наличии'), ('нет в наличии', 'нет в наличии')], max_length=255, null=True, verbose_name='Статус')),
                ('cost_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Себестоимость')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество продукта')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидна на продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='no_image.jpg', force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='product_images/', verbose_name='Основная фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография торава',
                'verbose_name_plural': 'Фотографии товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255, verbose_name='Характеристики товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характиристика торава',
                'verbose_name_plural': 'Характиристики товаров',
            },
        ),
    ]
