# Generated by Django 5.0.6 on 2024-10-19 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название главноного категория')),
            ],
            options={
                'verbose_name': 'Главная категория',
                'verbose_name_plural': 'Главная категория',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категория')),
            ],
            options={
                'verbose_name': 'Дочерняя категория',
                'verbose_name_plural': 'Дочерняя категория',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default=1, max_length=255, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(default=1, max_length=255, verbose_name='Материал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидка на продукт'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='products.category', verbose_name='Категория товара'),
        ),
    ]
