# Generated by Django 5.0.6 on 2024-10-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bigcategory_category_products_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='big_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_category_category', to='products.bigcategory', verbose_name='Выбрать главную категорию'),
        ),
    ]
