# Generated by Django 5.0.6 on 2024-10-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_big_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='big_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='products.bigcategory', verbose_name='Выбрать главную категорию'),
        ),
    ]
