# Generated by Django 5.0.6 on 2024-10-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_big_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Normal', 'Normal')], max_length=255, null=True, verbose_name='Статус товара'),
        ),
    ]
