# Generated by Django 5.0.6 on 2024-10-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_status',
            new_name='newest',
        ),
    ]
