# Generated by Django 5.0.6 on 2024-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_status_products_newest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='newest',
        ),
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
