# Generated by Django 5.0.6 on 2024-10-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productreview_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufactur',
            field=models.CharField(default=1, max_length=255, verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
