# Generated by Django 5.0.6 on 2024-10-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_manufactur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='manufactur',
            new_name='manufacturer',
        ),
    ]
