# Generated by Django 5.0.6 on 2024-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_manufactur_products_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('в наличии', 'В наличии'), ('нет в наличии', 'нет в наличии')], default=1, max_length=255, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
