# Generated by Django 5.0.6 on 2024-10-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, choices=[('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE'), ('BLUE', 'BLUE'), ('GRAY', 'GRAY'), ('RED', 'RED'), ('YELLOW', 'YELLOW')], default='BLACK', max_length=100, null=True, verbose_name='Цвет товара'),
        ),
    ]
