# Generated by Django 5.0.6 on 2024-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('GREEN', 'Green'), ('WHITE', 'White'), ('PURPLE', 'Purple'), ('BLUE', 'Blue'), ('GRAY', 'Gray'), ('RED', 'Red'), ('YELLOW', 'Yellow')], default='BLACK', max_length=100, null=True, verbose_name='Цвет товара'),
        ),
    ]
