# Generated by Django 5.0.6 on 2024-10-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_products_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
    ]
