# Generated by Django 5.0.6 on 2024-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Рейтинг'),
        ),
    ]
