# Generated by Django 5.0.6 on 2024-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='user/image', verbose_name='Фото профиля'),
            preserve_default=False,
        ),
    ]
