# Generated by Django 5.0.6 on 2024-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адарес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='stack',
            field=models.CharField(choices=[('Full Stack Developer', 'Full Stack Developer'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer')], default=1, max_length=255, verbose_name='Название Стека'),
            preserve_default=False,
        ),
    ]
