# Generated by Django 5.0.6 on 2024-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address_user_phone_user_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
    ]
