# Generated by Django 5.0.6 on 2024-11-11 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название проекта')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Бюджет')),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Complete', 'Complete'), ('Waiting', 'Waiting')], max_length=255, null=True, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to=settings.AUTH_USER_MODEL, verbose_name='Выбрать пользователя')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
