# Generated by Django 5.0.6 on 2024-11-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='date',
            new_name='created_at',
        ),
    ]
