# Generated by Django 5.0.6 on 2024-11-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='comment',
            new_name='text',
        ),
    ]
