# Generated by Django 5.0.6 on 2024-11-12 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usercomment_created_at_alter_usercomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_products', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
