# Generated by Django 5.0.6 on 2024-11-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usercomment_created_at_usercomment_profile_and_more'),
        ('users', '0017_usercomment_profile_alter_usercomment_user'),
    ]

    operations = [
    ]
