# Generated by Django 5.0.6 on 2024-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20241112_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='код'),
        ),
    ]
