# Generated by Django 5.0.6 on 2024-12-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_reset_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='created_at',
            new_name='created',
        ),
    ]
