# Generated by Django 5.0.6 on 2024-11-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('В ожидании', 'В ожидании'), ('В работе', 'В работе'), ('Завершено', 'Завершено')], max_length=255, null=True, verbose_name='Статус выполнения таска'),
        ),
    ]
