# Generated by Django 5.0.6 on 2024-11-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.CreateModel(
            name='TaskExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to='crm.todo', verbose_name='выбрать исполнителя')),
            ],
            options={
                'verbose_name': 'Исполнитель таска',
                'verbose_name_plural': 'Исполнители таска',
            },
        ),
    ]
