# Generated by Django 5.0.6 on 2024-11-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_taskexecutor_task_alter_taskexecutor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskexecutor',
            old_name='task',
            new_name='task_name',
        ),
    ]
