# Generated by Django 5.0.6 on 2024-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_todo_user_delete_taskexecutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
