# Generated by Django 5.0.6 on 2024-10-31 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0017_products_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('Лидогенерация', 'Лидогенерация'), ('Биллинг', 'Биллинг')], default='Лидогенерация', max_length=100, verbose_name='Тип биллинга')),
                ('billing_receipt_type', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка'), ('Неизвестно', 'Неизвестно')], default='Неизвестно', max_length=100, verbose_name='Вид получения товара')),
                ('billing_status', models.CharField(choices=[('В корзине', 'В корзине'), ('Оформлен', 'Оформлен'), ('Оплачен', 'Оплачен'), ('Доставлен', 'Доставлен'), ('Возврат', 'Возврат'), ('Неизвестно', 'Неизвестно')], default='В корзине', max_length=100, verbose_name='Статус заказа')),
                ('billing_payment_status', models.CharField(choices=[('Оплачен', 'Оплачен'), ('Не оплачен', 'Не оплачен'), ('Ошибка', 'Ошибка'), ('В исполнении', 'В исполнении')], default='В исполнении', max_length=100, verbose_name='Статус оплаты')),
                ('billing_payment', models.CharField(choices=[('Наличными в магазине', 'Наличными в магазине'), ('Наличными курьеру', 'Наличными курьеру'), ('Оплата картой курьеру', 'Оплата картой курьеру'), ('Оплата переводом', 'Оплата переводом'), ('Оплата в рассрочку', 'Оплата в рассрочку'), ('Картой Visa', 'Картой Visa'), ('Мбанк', 'Мбанк'), ('Optima 24', 'Optima 24'), ('О! Деньги', 'О! Деньги'), ('Bakai 24', 'Bakai 24'), ('Ошибка', 'Ошибка'), ('Неизвестно', 'Неизвестно')], default='Неизвестно', max_length=100, verbose_name='Способы оплаты')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефонный номер')),
                ('payment_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Код оплаты биллинга')),
                ('country', models.CharField(blank=True, default='Кыргызстан', max_length=255, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Квартира')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Индекс')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('delivery_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Стоимость доставки')),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('delivery_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата время доставки')),
                ('client_gave_money', models.IntegerField(blank=True, default=0, null=True, verbose_name='Клиент дал денег')),
                ('change_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сдача клиенту')),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Итоговая сумма')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания биллинга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Биллинг',
                'verbose_name_plural': 'Биллинги',
            },
        ),
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Отчет продажа товар',
                'verbose_name_plural': 'Отчеты продажи товаров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billings.billing',),
        ),
        migrations.CreateModel(
            name='BillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Итоговая цена товара')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_products', to='billings.billing', verbose_name='Биллинг')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_billings', to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Биллинг товара',
                'verbose_name_plural': 'Биллинги товаров',
            },
        ),
    ]
