# Generated by Django 5.0.6 on 2024-10-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='note',
        ),
        migrations.AddField(
            model_name='billing',
            name='city',
            field=models.CharField(blank=True, default='Ош', max_length=255, null=True, verbose_name='Город'),
        ),
    ]
