# Generated by Django 5.0.6 on 2024-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_remove_billing_note_billing_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
