# Generated by Django 5.0.6 on 2024-11-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='address',
        ),
    ]
