# Generated by Django 5.0.6 on 2024-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_remove_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_receipt_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка'), ('Неизвестно', 'Неизвестно')], default='Самовывоз', max_length=100, verbose_name='Вид получения товара'),
        ),
    ]
