# Generated by Django 5.0.6 on 2024-11-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_alter_billing_billing_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_receipt_type',
            field=models.CharField(choices=[('Неизвестно', 'Неизвестно'), ('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=100, verbose_name='Вид получения товара'),
        ),
    ]
