# Generated by Django 5.0.6 on 2024-11-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0006_alter_billing_billing_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_receipt_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка'), ('Неизвестно', 'Неизвестно')], default='Неизвестно', max_length=100, verbose_name='Вид получения товара'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='delivery_date_time',
            field=models.DateField(blank=True, null=True, verbose_name='Дата время доставки'),
        ),
    ]
