# Generated by Django 5.0.6 on 2024-11-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_alter_billing_billing_receipt_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Итоговая цена товаров'),
            preserve_default=False,
        ),
    ]
