# Generated by Django 5.0.6 on 2024-11-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0008_billingproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена товаров'),
        ),
    ]
