# Generated by Django 5.0.6 on 2024-11-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0009_alter_billingproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
