# Generated by Django 5.0.6 on 2024-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_alter_billingproduct_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='created',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
