# Generated by Django 5.0.6 on 2024-12-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0011_alter_billingproduct_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_billings', to='billings.billing', verbose_name='Биллинг'),
        ),
    ]
