# Generated by Django 5.0.6 on 2024-10-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, verbose_name='Название (доставка)')),
                ('description_1', models.TextField(verbose_name='Описание (доставка)')),
                ('title_2', models.CharField(max_length=255, verbose_name='Название (Возврат)')),
                ('description_2', models.TextField(verbose_name='Описание (Возврат)')),
                ('title_3', models.CharField(max_length=255, verbose_name='Название (Поддержка)')),
                ('description_3', models.TextField(verbose_name='Описание (Поддержка)')),
                ('title_4', models.CharField(max_length=255, verbose_name='Название (Оплата)')),
                ('description_4', models.TextField(verbose_name='Описание (Оплата)')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
