# Generated by Django 5.0.6 on 2024-11-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_calendarcategory_alter_calendar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='calendar',
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_status',
            field=models.CharField(choices=[('Срочный', 'Срочный'), ('Темный', 'Темный'), ('Приватный', 'Приватный'), ('Встречи', 'Встречи'), ('По желанию', 'По желанию'), ('Успешно', 'Успешно')], default=1, max_length=255, verbose_name='Статус события'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CalendarCategory',
        ),
    ]
