# Generated by Django 5.0.6 on 2024-11-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
