# Generated by Django 5.0.6 on 2024-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted_for_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted_for_sender',
            field=models.BooleanField(default=False),
        ),
    ]
